controller_manager:
  ros__parameters:
    update_rate: 100  # Frequência de atualização dos controladores (Hz)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dynamic_controller:
      type: dynamic_controller_plugin/DynamicControllerPlugin
      ros__parameters:
        use_sim_time: true
        joints:
          - J1
          - J2
          - J3
          - J4
          - J5
          - J6
          - J7
